name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build and Publish latest Docker image
        uses: TCPShield/gp-docker-action@1.1.13
        with:
          github-username: ${{ secrets.DOCKER_USERNAME }}
          github-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ghcr.io/setnemo/node
          image-tag: latest
          dockerfile: ./Dockerfile
